### ISSUE TITLE
Crash on ppc64 at basic_latin_to_ascii

### ISSUE THREAD

**Issue by stransky** [hsivonen/encoding_rs#45] opened 2019-12-17 14:44 UTC
There's crash at ppc64 arch, reported as https://bugzilla.mozilla.org/show_bug.cgi?id=1604488

Program received signal SIGSEGV, Segmentation fault.
basic_latin_to_ascii (src=<optimized out>, dst=<optimized out>, len=<optimized out>) at /home/komat/rpmbuild/BUILD/firefox-68.3.0/third_party/rust/encoding_rs/src/ascii.rs:264
264 let code_unit = *(src.add(offset));

**Comment by hsivonen** [comment] 2020-01-14 09:58
I'm closing this issue here, because the log in the Gecko bug suggests that encoding_rs is looping correctly and the problem is with what's passed into encoding_rs.

**Closed by hsivonen** 2020-01-14 09:58 UTC
