### ISSUE TITLE
feature request: ASCII-filter

### ISSUE THREAD

**Issue by getreu** [hsivonen/encoding_rs#46] opened 2020-01-13 13:11 UTC
I recently migrated [Stringsext, a GNU Strings Alternative with Multi-Byte-Encoding Support](https://github.com/getreu/stringsext) from [rust-encoding](https://github.com/lifthrasiir/rust-encoding) to [encoding_rs](https://github.com/hsivonen/encoding_rs/).

A string-extraction-tool like Stringsext needs a fast ASCII-only filter. As I did not find a way to extend `encoding_rs`-encodings, I simulate the `ASCII` with `x-user-defined`. This is slow and consumes a lot memory.

Could it be possible to add natively ASCII-encoding?

**Comment by hsivonen** [comment] 2020-01-13 13:30
> A string-extraction-tool like Stringsext needs a fast ASCII-only filter.

Do you mean function that copies ASCII from one buffer to another and signals an error upon finding a non-ASCII character?

> Could it be possible to add natively ASCII-encoding?

Adding an ASCII-only `Encoding` is [out of scope](https://github.com/hsivonen/encoding_rs/blob/master/CONTRIBUTING.md#no-encodings-beyond-the-encoding-standard). However, the `mem` module has [`encoding_rs::mem::copy_ascii_to_ascii`](https://docs.rs/encoding_rs/0.8.22/encoding_rs/mem/fn.copy_ascii_to_ascii.html).

**Comment by getreu** [comment] 2020-01-13 13:47
> Do you mean function that copies ASCII from one buffer to another and signals an error upon finding a non-ASCII character?

Yes.

>>    Could it be possible to add natively ASCII-encoding?

> Adding an ASCII-only Encoding is out of scope. However, the mem module has `encoding_rs::mem::copy_ascii_to_ascii`.

Thank you. Using `copy_ascii_to_ascii`  separately makes my code slower and more complicated, because it adds at least one redirection. I understand, that you want to limit the supported encodings. But the ASCII-encoding, is already implemented in your code (cf. above); it just needs to be listed?

**Comment by hsivonen** [comment] 2020-01-13 14:28
> But the ASCII-encoding, is already implemented in your code (cf. above); it just needs to be listed?

Making ASCII an `Encoding` would break the property that you can trust the type system that an `Encoding` is an Encoding Standard encoding and won't exhibit behaviors that Encoding Standard encodings don't exhibit. I know this doesn't meet all character encoding-related use cases, but I've tried to make the documentation very up front in terms of expectations setting that this crate isn't going to add non-Encoding Standard encodings.

Creating a wrapper type that delegates to encoding_rs for Encoding Standard encodings and does something else for other does have the downside of an extra indirection per call, but the as far as making code slower goes, the cost of the indirection should be tiny relative to the cost of converting/copying the data.

For example, the [`charset`](https://crates.io/crates/charset) crate for decoding emails has a wrapper type that supports UTF-7 and delegation to encoding_rs.

**Closed by hsivonen** 2020-01-13 14:28 UTC

**Comment by getreu** [comment] 2020-01-13 16:32
Yes, I guess my use-case is not very common.
In Stringsext, an extra indirection in the inner-loop - parsing TB of data in small chunks - has a huge cost! This is why at the moment I emulate ASCII with `x-user-defined`. The ASCII scanner is less often used than UTF-8 for example.
In the first version of Stringsext with `rust-encoding` I could [add an ASCII decoder](https://github.com/getreu/stringsext/blob/4a61c180a4fea135a7c28aed614339b42379bdec/src/codec/ascii.rs) myself.
I could not find out how to do this with `encoding_rs`. Is it possible?

**Comment by hsivonen** [comment] 2020-01-14 07:43
It's _by design_ impossible with the encoding_rs types. That is, the encoding_rs types give you a guarantee of behavior, so you don't get to break that guarantee.

The way to add behaviors is to create new types that delegate to encoding_rs types for those operations that aren't the operations you want to add.

The [`charset`](https://crates.io/crates/charset) crate mentioned above has an example of this: It's `Charset` type wraps the `Encoding` type. It intentionally doesn't provide a wrapper for `Decoder`, because implementing a streaming UTF-7 decoder is too complicated relative to realistic email use cases (i.e. buffering an entire email message is OK and generally how apps that handle email work anyway). However, your wrapper types could wrap `Decoder`, too, if you so choose.
