### ISSUE TITLE
Switch from simd to packed_simd

### ISSUE THREAD

**Issue by jrmuizel** [hsivonen/encoding_rs#23] opened 2017-10-27 17:19 UTC
stdsimd is the replacement for simd

**Comment by hsivonen** [comment] 2017-11-01 12:03
Thanks. I hadn't noticed that `stdsimd` had gained NEON support.

To my surprise, there are no longer distinct boolean vector types in `stdsimd`. They seem to be gone from WebAssembly SIMD, too!

Yet, I don't see analogs for the `all()` and `any()` methods that the boolean vectors had in the `simd` crate.

I guess I should find out the rationale for the change and what the design intent is for replacements for `all()` and `any()`.

**Comment by BurntSushi** [comment] 2017-11-01 12:07
@hsivonen The [current plan](https://github.com/rust-lang-nursery/stdsimd/issues/159) is to be as conservative as possible. I don't think the OP, "stdsimd is the replacement for simd," is accurate as of present. My suspicion is that the next phase is probably going to be something like, "stable, but inconvenient portability story."

**Comment by hsivonen** [comment] 2018-03-08 11:40
[Portable SIMD](https://github.com/rust-lang-nursery/stdsimd/pull/338) got merged in to `stdsimd`, so I'm going to see if encoding_rs can now be ported over.

**Comment by hsivonen** [comment] 2018-03-09 09:00
Yesterday, I failed to notice that in `stdsimd` comparing two `u16x8`s yields `b8x8` and there is no `b16x8`. Commented on the [`stdsimd` issue](https://github.com/rust-lang-nursery/stdsimd/issues/185).

**Comment by ignatenkobrain** [comment] 2018-07-29 06:19
any news here?

**Comment by hsivonen** [comment] 2018-08-07 08:48
No news yet. I was away for a bit and will need to catch up on the situation regarding `any()`/`all()` inlining with `stdsimd`, especially in the ARMv7+NEON case.

**Comment by gnzlbg** [comment] 2018-08-14 15:12
@hsivonen packed_simd fixed all of those issues a while ago, and provides many many new features (shuffles with run-time indices, portable vector gather/scatters, ...). 

Let me know if that isn't the case, I think the simd crate can pretty much be removed. All its features are now available in `packed_simd`, all examples have been ported, etc.

**Comment by hsivonen** [comment] 2018-08-28 12:03
@gnzlbg, can I now get fast boolean reductions on ARMv7+NEON without having the standard library [compiled with NEON enabled](https://github.com/rust-lang/rust/pull/49902)? I.e. do I need to revive that PR and debug the Android Docker issue?

**Comment by gnzlbg** [comment] 2018-08-28 12:27
I just released version `0.2` of `packed_simd`, you should prefer that over the `0.1` version, which did not allow doing that (because it relied on `coresimd` as a git dependency, which had to be disabled for `crates.io`).

> I.e. do I need to revive that PR and debug the Android Docker issue?

Yeah, you should (its almost there, and if you have access to a linux workstation debugging locally shouldn't be too hard). This is a short term workaround that will never work on stable.

**Comment by gnzlbg** [comment] 2018-09-12 13:55
Which `packed_simd` features are you enabling ? Which target? Which `RUSTFLAGS` ?

Could you extract the code of those three benchmarks into its own crate ?

**Comment by gnzlbg** [comment] 2018-09-12 13:57
Also the worst benchmark appears to be ` bench_mem_is_utf8_latin1_true_3 `

**Comment by gnzlbg** [comment] 2018-09-12 14:11
I've left a couple of comments in your branch, there is one suspicious function there that might be causing the regression, we should take a closer look at that comparing the output of the simd and packed_simd crates for the version with and without select (without select, both crates should generate exactly the same code).

**Comment by hsivonen** [comment] 2018-09-13 07:50
> Which packed_simd features are you enabling ? Which target? Which RUSTFLAGS ?

The above numbers were with the `into_bits` feature enabled, `x86_64-unknown-linux-gnu` target, `-C opt_level=2` in `RUSTFLAGS` on Ubuntu 18.04 on Intel Core i7-4770 @ 3.40 GHz.

> Could you extract the code of those three benchmarks into its own crate ?

I'll try to minimize the test case.

> Also the worst benchmark appears to be `bench_mem_is_utf8_latin1_true_3`

Indeed. That benchmark shouldn't even run SIMD code, because 3 < 16, which is why I speculated about prediction heuristics flipping or something.

> I've left a couple of comments in your branch

Thanks!

> there is one suspicious function there that might be causing the regression

The suspicious function affects only `x-user-defined` to UTF-16 decoding and is performance-neutral. (The change is based on previous advice from you. :-)

**Comment by gnzlbg** [comment] 2018-09-13 07:56
> I'll try to minimize the test case.

Thank you! Feel free to open an issue in `packed_simd` and we'll look at it.

**Comment by hsivonen** [comment] 2018-09-13 08:28
On aarch64 (ThunderX), the fluctuation of the numbers is a bit larger, so there's are more changes in both directions with the 2-percentage-point threshold. I'm not too worried about that.

Instead of `bench_mem_is_utf8_latin1_N` with small N regressing, the closely related `bench_mem_is_str_latin1_true_N` with small N regresses.

(These are with the horizontal max intrinsics instead of the portable horizontal max operations.)

**Comment by gnzlbg** [comment] 2018-09-13 09:00
@hsivonen could you try again with `packed_simd` master branch for both x86 and aarch64?

**Comment by gnzlbg** [comment] 2018-09-13 09:01
Maybe there is some inlining issue / target-feature issue popping up, since the `simd` crate uses `platform-intrinsics` and the `packed_simd` crate uses `core::arch`, so maybe `RUSTFLAGS` have something to do with this.

**Comment by hsivonen** [comment] 2018-09-13 14:07
On `x86_64` the regressions go away when building with the `coresimd` feature and without `RUSTFLAGS`. Up next: Figuring out which one of those makes the difference.

**Comment by hsivonen** [comment] 2018-09-24 12:07
It seems that `opt_level=2` is the problem. With or without `coresimd` feature flag affects which tests regress, though.

**Comment by hsivonen** [comment] 2018-10-15 10:46
Sorry about the delay. After updating `packed_simd` (but staying on `rustc` from the turn of the month, because packaging for `clippy` blocks updates), I still see perf regressions at `opt_level=2` with `encoding_bench` (and now also a regression of `bench_mem_utf16_valid_up_to_ascii_1000` at `opt_level=3`). However, when trying to create a smaller test case for the `opt_level=2` regressions by extracting the code to a [single-file crate](https://github.com/hsivonen/bench_packed) the regressions go away.

Still more to investigate.

Meanwhile: It appears that `cargo` is getting the capability to set per-crate `opt_level`, so maybe this is going to be solved by building [`encoding_rs` at `opt_level=3`](https://bugzilla.mozilla.org/show_bug.cgi?id=1498985) in Firefox. OTOH, a build system peer considered `packed_simd`'s compatibilily policy with only the latest nightly as a blocker, so it seems that migration from `simd` to `packed_simd` has to wait until `packed_simd` makes it into the standard library.

**Comment by BurntSushi** [comment] 2018-10-15 11:00
> OTOH, a build system peer considered packed_simd's compatibilily policy with only the latest nightly as a blocker, so it seems that migration from simd to packed_simd has to wait until packed_simd makes it into the standard library.

I thought that was `simd`'s policy also? At least, in the past, IIRC, if a nightly came out that broke `simd`, we would fix it without necessarily keeping compatibility with older nightlies.

It may be that `packed_simd` makes this more of a problem in practice since it is being actively developed.

**Comment by gnzlbg** [comment] 2018-10-15 11:11
> I thought that was simd's policy also?

It is `simd`'s crate policy and `core::arch::{arm, aarch64}` policy as well.

**Comment by hsivonen** [comment] 2018-10-15 12:41
> However, when trying to create a smaller test case for the `opt_level=2` regressions by extracting the code to a single-file crate, the regressions go away.

Specifically, the code using `simd` and the code using `packed_simd` compile to identical assembly except for label naming.

> I thought that was `simd`'s policy also?

In practice, `simd` isn't being developed further, so it doesn't adopt new Rust features that would require a new compiler version and, OTOH, `rustc` hasn't broken the relevant parts of `simd` in a long while.

What's the practical breakage situation with `packed_simd`?

**Comment by gnzlbg** [comment] 2018-10-15 13:38
> What's the practical breakage situation with packed_simd?

The library cannot build on stable Rust, only on nightly. It is still being developed, with new features, bug fixes, and performance fixes being added every now and then. Sometimes these require patching rustc, and we tend to then start using the features as soon as the next nightly is released, and until now the only stakeholders that complain are the `rand` developers, but we tend to let them know when breaking changes happen and we help with the PR required to upgrade. This isn't too hard because `rand` `unstable` follows the latest nightly anyways. 

If a bigger stake holder (e.g. servo / firefox) with stricter "unstable stability requirements" starts depending on `packed_simd`, then we'll have to adapt our workflow around those requirements. 

For example, we could add a CI build bot to test the nightly version used by stakeholders, and add any new features that would break that behind a feature gate. Once all stakeholders upgrade, then we could remove those feature gates.

**Comment by hsivonen** [comment] 2018-10-15 15:41
> The library cannot build on stable Rust, only on nightly.

Indeed, `packed_simd` doesn't build with 1.29.2 even with `RUSTC_BOOTSTRAP=1`.

> Sometimes these require patching rustc, and we tend to then start using the features as soon as the next nightly is released

From a Firefox perspective, it seems to me that the main constraint is at the other end: For how long does a given snapshot of `packed_simd` stay compilable with future versions of Rust?

[Firefox CI uses stable Rust and starts requiring a new Rust version two weeks after its release.](https://wiki.mozilla.org/Rust_Update_Policy_for_Firefox) `encoding_rs` and `simd` opt into nightly features on stable Rust using `RUSTC_BOOTSTRAP=1`. Additionally, Firefox developers may use a recent-ish nightly Rust locally.

As a result, it's impractical to use a crate whose Rust compatibility doesn't span the current stable with `RUSTC_BOOTSTRAP=1` and the current nightly.

**Comment by hsivonen** [comment] 2018-10-19 07:15
My current theory is this:

If a simd-using function that's visible to outside the crate has been annotated as `#[inline]` to enable cross-crate inlining and if the benchmarking harness is in a different crate so that cross-crate inlining applies, the version using the `simd` crate gains some advantage that `packed_simd` does not. This advantage is not shown if any of the following are true:

 * The benchmarking harness and the code being benchmarked are in the same crate.
 * The benchmarking harness and the code being benchmarked are in different crates but there's no cross-crate inlining.
 * `opt_level=3`

So for now, I consider this a case of invalid benchmarking (inlining resulting in a scenario that's unlikely to be representative of real-world use).

In other news, with the `into_bits` feature of `packed_simd` enabled, the `packed_simd` branch of encoding_rs now has no direct calls to `transmute`. Going forward, I'm hoping that primitive slice's `align_to` and `chunks_exact` together with `packed_simd` load/store from slice features will allow for a lot of `unsafe` code to be written as equally-performant safe code.

**Comment by gnzlbg** [comment] 2018-10-19 07:47
> For how long does a given snapshot of packed_simd stay compilable with future versions of Rust?

For as long as Rust does not introduce a change that breaks `packed_simd`. `packed_simd` is a Rust2018 crate, so there have been a lot of these changes in the last couple of months as nightly features have been renamed, stabilized, dropped, etc. 

Otherwise, there are periods of higher "rustc simd activity", were newer simd features are implemented, typically followed by a couple of months of reaping the results.

**Comment by hsivonen** [comment] 2019-01-21 10:33
The failing function is:

```rust
        #[inline(always)]
        pub fn simd_pack(a: u16x8, b: u16x8) -> u8x16 {
            unsafe {
                let first: u8x16::from_bits(a);
                let second: u8x16::from_bits(b);
                shuffle!(
                    first,
                    second,
                    [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]
                )
            }
}
```

Which previously compiled on aarch64. I'm going to try again on that ISA.

**Comment by gnzlbg** [comment] 2019-01-21 10:37
> Which previously compiled on aarch64. I'm going to try again on that ISA.

I think you want `let first = u8x16::from_bits(a);` instead of `let first: u8x16::from_bits(a);` 🤣 I really do hope that this code did not used to compile before 😛

**Comment by gnzlbg** [comment] 2019-01-21 11:03
FWIW the error message could have been a lot clearer, you might want to fill in an issue in rust-lang/rust upstream about it.

**Comment by hsivonen** [comment] 2019-01-21 11:08
OK. With this problem fixed, it compiles for `thumbv7neon` but compiling for `aarch64` fails, because the compiler tries to make a 1 GB memory allocation when compiling `packed_simd` 0.3.1.

Is this a previously known problem?

memory allocation of 1073741824 bytes failed
error: Could not compile `packed_simd`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name packed_simd /home/hsivonen/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd-0.3.1/src/lib.rs --color always --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="into_bits"' -C metadata=2b4eed31d1b1027b -C extra-filename=-2b4eed31d1b1027b --out-dir /home/hsivonen/Projects/encoding_rs/target/debug/deps -L dependency=/home/hsivonen/Projects/encoding_rs/target/debug/deps --extern cfg_if=/home/hsivonen/Projects/encoding_rs/target/debug/deps/libcfg_if-e6de5e9a7e5221ad.rlib --cap-lints allow` (signal: 6, SIGABRT: process abort signal)

**Comment by gnzlbg** [comment] 2019-01-21 11:21
> Is this a previously known problem?

I haven't seen that one before, which target are you using? aarch64-unknown-linux-android ?

**Comment by hsivonen** [comment] 2019-01-21 12:15
Hmm. Trying to compile on an x86_64 host both for aarch64 and x86_64 shows that rustc's memory usage climbs to a bit over 2 GB when compiling `packed_simd` 0.3.1.

I'm pretty sure that 0.3.0 with earlier rustc didn't have this problem, but given the earlier comments today, I no longer trust myself having actually built this code on aarch64 previously.

I'll see if I can buy more RAM for my aarch64 VM, since it's annoying to run `cargo bench` with cross-compile.

**Comment by gnzlbg** [comment] 2019-01-21 12:17
Sadly it is not easy to only build a "subset" of `packed_simd` (say just 128-bit wide vector support). 

I've been thinking about making `packed_simd` "lazy", such that code is monomorphized when a user uses a type instead of always at the build time of `packed_simd`, but that's a trade-off.

**Comment by hsivonen** [comment] 2019-01-21 12:36
> Sadly it is not easy to only build a "subset" of `packed_simd` (say just 128-bit wide vector support).

Maybe I should try commenting out code to get _some_ results.

> I'll see if I can buy more RAM for my aarch64 VM

The provider represents their aarch64 capacity as "out of stock", so can't get more RAM today.

**Comment by gnzlbg** [comment] 2019-01-21 12:41
> Maybe I should try commenting out code to get some results.

You can try commenting out certain APIs, e.g., in `src/api.rs` but commenting out vector widths won't easily work (some features like vectors of pointers couple vectors of different lengths).

**Comment by hsivonen** [comment] 2019-01-22 10:52
> FWIW the error message could have been a lot clearer, you might want to fill in an issue in rust-lang/rust upstream about it.

[Filed](https://github.com/rust-lang/rust/issues/57828)

**Comment by hsivonen** [comment] 2019-01-22 11:13
Filed an [issue](https://github.com/rust-lang/rust/issues/57829) about rustc memory usage when compiling `packed_simd`.

**Comment by hsivonen** [comment] 2019-01-28 13:06
In case ripgrep users find their way here:

This [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1521249) has "Depends on" and "See also" fields that point to relevant bugs/issues that are blocking migration at present.

**Comment by gnzlbg** [comment] 2019-01-30 12:39
> correlate with horizontal boolean reduction

From which types (integers, floats, etc.) are the masks created ?

**Comment by hsivonen** [comment] 2019-01-30 13:30
Discovered so far: The presence of thumb trampolines is the very first thing that stands out in the assembly. I need to go back and run the `simd` crate baseline in thumb mode.

> From which types (integers, floats, etc.) are the masks created ?

From `u8x16` and `u16x8`.

> Unrelated update, some stdsimd refactorings have landed in nightly, and packed_simd should start to build again properly soon.

It seems to be in the present nightly already. Thanks!

**Comment by hsivonen** [comment] 2019-01-30 13:33
> The presence of thumb trampolines is the very first thing that stands out in the assembly.

Once we get past the trampolines on the crate boundary, inlining from `core::arch` and `packed_simd` appears to have worked.

**Comment by hsivonen** [comment] 2019-01-30 16:20
Thumb-to-Thumb comparison still shows a regression.

**Comment by hsivonen** [comment] 2019-01-30 16:34
With the `simd` crate, building `encoding_rs` with `--release` and `--emit asm` emits one `.s` file. With `packed_simd` 31 `.rcgu.s` files are emitted. https://doc.rust-lang.org/rustc/codegen-options/index.html suggests that multiple codegen-units can lead to slower code. `RUSTFLAGS='-C codegen-units=1'` does not appear to change things.

**Comment by gnzlbg** [comment] 2019-01-30 17:35
@hsivonen can you fill a rust-lang/rust about the multiple codegen-units issue? cc @mw

**Comment by hsivonen** [comment] 2019-01-31 12:50
> can you fill a rust-lang/rust about the multiple codegen-units issue?

[Filed](https://github.com/rust-lang/rust/issues/58023)

**Comment by hsivonen** [comment] 2019-02-05 11:06
`encoding_rs::mem::copy_ascii_to_ascii` regresses significantly. To start with, the inlining situation differs. With manual always/never choices, the results are counter-intuitive (`never` faster than `always` with `simd`), but `simd` is still faster:

simd, inline(never)
test bench_mem_copy_ascii_to_ascii_1000                ... bench:     120,045 ns/iter (+/- 686) = 4165 MB/s

simd, inline(always)
test bench_mem_copy_ascii_to_ascii_1000                ... bench:     129,785 ns/iter (+/- 5,024) = 3852 MB/s

packed_simd, inline(never)
test bench_mem_copy_ascii_to_ascii_1000                ... bench:     164,637 ns/iter (+/- 3,623) = 3036 MB/s

packed_simd, inline(always)
test bench_mem_copy_ascii_to_ascii_1000                ... bench:     160,739 ns/iter (+/- 9,820) = 3110 MB/s

For the never cases, here's the assembly from `objdump` of the benching binary.

`simd`:

```asm
0006c160 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE>:
   6c160:	b580      	push	{r7, lr}
   6c162:	428b      	cmp	r3, r1
   6c164:	d36a      	bcc.n	6c23c <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE+0xdc>
   6c166:	468e      	mov	lr, r1
   6c168:	2910      	cmp	r1, #16
   6c16a:	d31b      	bcc.n	6c1a4 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE+0x44>
   6c16c:	f002 030f 	and.w	r3, r2, #15
   6c170:	f1ae 0c10 	sub.w	ip, lr, #16
   6c174:	0701      	lsls	r1, r0, #28
   6c176:	d01a      	beq.n	6c1ae <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE+0x4e>
   6c178:	b373      	cbz	r3, 6c1d8 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE+0x78>
   6c17a:	2300      	movs	r3, #0
   6c17c:	18c1      	adds	r1, r0, r3
   6c17e:	f921 0a0f 	vld1.8	{d0-d1}, [r1]
   6c182:	ef89 2050 	vshr.s8	q1, q0, #7
   6c186:	ff02 2a03 	vpmax.u8	d2, d2, d3
   6c18a:	ff02 2a00 	vpmax.u8	d2, d2, d0
   6c18e:	ee12 1b10 	vmov.32	r1, d2[0]
   6c192:	2900      	cmp	r1, #0
   6c194:	d14a      	bne.n	6c22c <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE+0xcc>
   6c196:	18d1      	adds	r1, r2, r3
   6c198:	3310      	adds	r3, #16
   6c19a:	4563      	cmp	r3, ip
   6c19c:	f901 0a0f 	vst1.8	{d0-d1}, [r1]
   6c1a0:	d9ec      	bls.n	6c17c <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE+0x1c>
   6c1a2:	e043      	b.n	6c22c <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE+0xcc>
   6c1a4:	2300      	movs	r3, #0
   6c1a6:	4573      	cmp	r3, lr
   6c1a8:	d342      	bcc.n	6c230 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE+0xd0>
   6c1aa:	4670      	mov	r0, lr
   6c1ac:	bd80      	pop	{r7, pc}
   6c1ae:	b33b      	cbz	r3, 6c200 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE+0xa0>
   6c1b0:	2300      	movs	r3, #0
   6c1b2:	18c1      	adds	r1, r0, r3
   6c1b4:	f921 0acf 	vld1.64	{d0-d1}, [r1]
   6c1b8:	ef89 2050 	vshr.s8	q1, q0, #7
   6c1bc:	ff02 2a03 	vpmax.u8	d2, d2, d3
   6c1c0:	ff02 2a00 	vpmax.u8	d2, d2, d0
   6c1c4:	ee12 1b10 	vmov.32	r1, d2[0]
   6c1c8:	bb81      	cbnz	r1, 6c22c <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE+0xcc>
   6c1ca:	18d1      	adds	r1, r2, r3
   6c1cc:	3310      	adds	r3, #16
   6c1ce:	4563      	cmp	r3, ip
   6c1d0:	f901 0a0f 	vst1.8	{d0-d1}, [r1]
   6c1d4:	d9ed      	bls.n	6c1b2 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE+0x52>
   6c1d6:	e029      	b.n	6c22c <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE+0xcc>
   6c1d8:	2300      	movs	r3, #0
   6c1da:	18c1      	adds	r1, r0, r3
   6c1dc:	f921 0a0f 	vld1.8	{d0-d1}, [r1]
   6c1e0:	ef89 2050 	vshr.s8	q1, q0, #7
   6c1e4:	ff02 2a03 	vpmax.u8	d2, d2, d3
   6c1e8:	ff02 2a00 	vpmax.u8	d2, d2, d0
   6c1ec:	ee12 1b10 	vmov.32	r1, d2[0]
   6c1f0:	b9e1      	cbnz	r1, 6c22c <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE+0xcc>
   6c1f2:	18d1      	adds	r1, r2, r3
   6c1f4:	3310      	adds	r3, #16
   6c1f6:	4563      	cmp	r3, ip
   6c1f8:	f901 0acf 	vst1.64	{d0-d1}, [r1]
   6c1fc:	d9ed      	bls.n	6c1da <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE+0x7a>
   6c1fe:	e015      	b.n	6c22c <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE+0xcc>
   6c200:	2300      	movs	r3, #0
   6c202:	18c1      	adds	r1, r0, r3
   6c204:	f921 0acf 	vld1.64	{d0-d1}, [r1]
   6c208:	ef89 2050 	vshr.s8	q1, q0, #7
   6c20c:	ff02 2a03 	vpmax.u8	d2, d2, d3
   6c210:	ff02 2a00 	vpmax.u8	d2, d2, d0
   6c214:	ee12 1b10 	vmov.32	r1, d2[0]
   6c218:	b941      	cbnz	r1, 6c22c <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE+0xcc>
   6c21a:	18d1      	adds	r1, r2, r3
   6c21c:	3310      	adds	r3, #16
   6c21e:	4563      	cmp	r3, ip
   6c220:	f901 0acf 	vst1.64	{d0-d1}, [r1]
   6c224:	d9ed      	bls.n	6c202 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE+0xa2>
   6c226:	e001      	b.n	6c22c <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE+0xcc>
   6c228:	54d1      	strb	r1, [r2, r3]
   6c22a:	3301      	adds	r3, #1
   6c22c:	4573      	cmp	r3, lr
   6c22e:	d2bc      	bcs.n	6c1aa <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE+0x4a>
   6c230:	56c1      	ldrsb	r1, [r0, r3]
   6c232:	2900      	cmp	r1, #0
   6c234:	daf8      	bge.n	6c228 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE+0xc8>
   6c236:	469e      	mov	lr, r3
   6c238:	4670      	mov	r0, lr
   6c23a:	bd80      	pop	{r7, pc}
   6c23c:	4803      	ldr	r0, [pc, #12]	; (6c24c <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE+0xec>)
   6c23e:	2130      	movs	r1, #48	; 0x30
   6c240:	4a03      	ldr	r2, [pc, #12]	; (6c250 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17he774493b8d7dcf7bE+0xf0>)
   6c242:	4478      	add	r0, pc
   6c244:	447a      	add	r2, pc
   6c246:	f7ff fefb 	bl	6c040 <_ZN3std9panicking11begin_panic17hb6db914fa10d35c1E>
   6c24a:	defe      	udf	#254	; 0xfe
   6c24c:	009c918c 	.word	0x009c918c
   6c250:	009f3988 	.word	0x009f3988
```

`packed_simd`:

```asm
00056314 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E>:
   56314:	b570      	push	{r4, r5, r6, lr}
   56316:	428b      	cmp	r3, r1
   56318:	f0c0 8082 	bcc.w	56420 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E+0x10c>
   5631c:	468e      	mov	lr, r1
   5631e:	2910      	cmp	r1, #16
   56320:	d320      	bcc.n	56364 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E+0x50>
   56322:	f002 030f 	and.w	r3, r2, #15
   56326:	f1ae 0c10 	sub.w	ip, lr, #16
   5632a:	0701      	lsls	r1, r0, #28
   5632c:	d01f      	beq.n	5636e <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E+0x5a>
   5632e:	b3cb      	cbz	r3, 563a4 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E+0x90>
   56330:	2300      	movs	r3, #0
   56332:	18c1      	adds	r1, r0, r3
   56334:	f961 0a0f 	vld1.8	{d16-d17}, [r1]
   56338:	efc9 2070 	vshr.s8	q9, q8, #7
   5633c:	ee33 1b90 	vmov.32	r1, d19[1]
   56340:	ee32 4b90 	vmov.32	r4, d18[1]
   56344:	ee13 5b90 	vmov.32	r5, d19[0]
   56348:	ee12 6b90 	vmov.32	r6, d18[0]
   5634c:	4321      	orrs	r1, r4
   5634e:	ea46 0405 	orr.w	r4, r6, r5
   56352:	4321      	orrs	r1, r4
   56354:	d15c      	bne.n	56410 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E+0xfc>
   56356:	18d1      	adds	r1, r2, r3
   56358:	3310      	adds	r3, #16
   5635a:	4563      	cmp	r3, ip
   5635c:	f941 0a0f 	vst1.8	{d16-d17}, [r1]
   56360:	d9e7      	bls.n	56332 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E+0x1e>
   56362:	e055      	b.n	56410 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E+0xfc>
   56364:	2300      	movs	r3, #0
   56366:	4573      	cmp	r3, lr
   56368:	d354      	bcc.n	56414 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E+0x100>
   5636a:	4670      	mov	r0, lr
   5636c:	bd70      	pop	{r4, r5, r6, pc}
   5636e:	b39b      	cbz	r3, 563d8 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E+0xc4>
   56370:	2300      	movs	r3, #0
   56372:	18c1      	adds	r1, r0, r3
   56374:	f961 0acf 	vld1.64	{d16-d17}, [r1]
   56378:	efc9 2070 	vshr.s8	q9, q8, #7
   5637c:	ee33 1b90 	vmov.32	r1, d19[1]
   56380:	ee32 4b90 	vmov.32	r4, d18[1]
   56384:	ee13 5b90 	vmov.32	r5, d19[0]
   56388:	ee12 6b90 	vmov.32	r6, d18[0]
   5638c:	4321      	orrs	r1, r4
   5638e:	ea46 0405 	orr.w	r4, r6, r5
   56392:	4321      	orrs	r1, r4
   56394:	d13c      	bne.n	56410 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E+0xfc>
   56396:	18d1      	adds	r1, r2, r3
   56398:	3310      	adds	r3, #16
   5639a:	4563      	cmp	r3, ip
   5639c:	f941 0a0f 	vst1.8	{d16-d17}, [r1]
   563a0:	d9e7      	bls.n	56372 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E+0x5e>
   563a2:	e035      	b.n	56410 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E+0xfc>
   563a4:	2300      	movs	r3, #0
   563a6:	18c1      	adds	r1, r0, r3
   563a8:	f961 0a0f 	vld1.8	{d16-d17}, [r1]
   563ac:	efc9 2070 	vshr.s8	q9, q8, #7
   563b0:	ee33 1b90 	vmov.32	r1, d19[1]
   563b4:	ee32 4b90 	vmov.32	r4, d18[1]
   563b8:	ee13 5b90 	vmov.32	r5, d19[0]
   563bc:	ee12 6b90 	vmov.32	r6, d18[0]
   563c0:	4321      	orrs	r1, r4
   563c2:	ea46 0405 	orr.w	r4, r6, r5
   563c6:	4321      	orrs	r1, r4
   563c8:	d122      	bne.n	56410 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E+0xfc>
   563ca:	18d1      	adds	r1, r2, r3
   563cc:	3310      	adds	r3, #16
   563ce:	4563      	cmp	r3, ip
   563d0:	f941 0acf 	vst1.64	{d16-d17}, [r1]
   563d4:	d9e7      	bls.n	563a6 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E+0x92>
   563d6:	e01b      	b.n	56410 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E+0xfc>
   563d8:	2300      	movs	r3, #0
   563da:	18c1      	adds	r1, r0, r3
   563dc:	f961 0acf 	vld1.64	{d16-d17}, [r1]
   563e0:	efc9 2070 	vshr.s8	q9, q8, #7
   563e4:	ee33 1b90 	vmov.32	r1, d19[1]
   563e8:	ee32 4b90 	vmov.32	r4, d18[1]
   563ec:	ee13 5b90 	vmov.32	r5, d19[0]
   563f0:	ee12 6b90 	vmov.32	r6, d18[0]
   563f4:	4321      	orrs	r1, r4
   563f6:	ea46 0405 	orr.w	r4, r6, r5
   563fa:	4321      	orrs	r1, r4
   563fc:	d108      	bne.n	56410 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E+0xfc>
   563fe:	18d1      	adds	r1, r2, r3
   56400:	3310      	adds	r3, #16
   56402:	4563      	cmp	r3, ip
   56404:	f941 0acf 	vst1.64	{d16-d17}, [r1]
   56408:	d9e7      	bls.n	563da <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E+0xc6>
   5640a:	e001      	b.n	56410 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E+0xfc>
   5640c:	54d1      	strb	r1, [r2, r3]
   5640e:	3301      	adds	r3, #1
   56410:	4573      	cmp	r3, lr
   56412:	d2aa      	bcs.n	5636a <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E+0x56>
   56414:	56c1      	ldrsb	r1, [r0, r3]
   56416:	2900      	cmp	r1, #0
   56418:	daf8      	bge.n	5640c <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E+0xf8>
   5641a:	469e      	mov	lr, r3
   5641c:	4670      	mov	r0, lr
   5641e:	bd70      	pop	{r4, r5, r6, pc}
   56420:	4803      	ldr	r0, [pc, #12]	; (56430 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E+0x11c>)
   56422:	2130      	movs	r1, #48	; 0x30
   56424:	4a03      	ldr	r2, [pc, #12]	; (56434 <_ZN11encoding_rs3mem19copy_ascii_to_ascii17h490246fe632404a1E+0x120>)
   56426:	4478      	add	r0, pc
   56428:	447a      	add	r2, pc
   5642a:	f000 f9bb 	bl	567a4 <_ZN3std9panicking11begin_panic17hd61fceca69156f6cE>
   5642e:	defe      	udf	#254	; 0xfe
   56430:	009a3b71 	.word	0x009a3b71
   56434:	009ebd14 	.word	0x009ebd14
```

The very first observation: `packed_simd` generates more instructions.

**Comment by hsivonen** [comment] 2019-02-05 11:10
OK, so the horizontal reductions generate worse code under `packed_simd`.

`simd`:

```asm
   6c17e:	f921 0a0f 	vld1.8	{d0-d1}, [r1]
   6c182:	ef89 2050 	vshr.s8	q1, q0, #7
   6c186:	ff02 2a03 	vpmax.u8	d2, d2, d3
   6c18a:	ff02 2a00 	vpmax.u8	d2, d2, d0
   6c18e:	ee12 1b10 	vmov.32	r1, d2[0]
   6c192:	2900      	cmp	r1, #0
```

`packed_simd`:

```asm
   56334:	f961 0a0f 	vld1.8	{d16-d17}, [r1]
   56338:	efc9 2070 	vshr.s8	q9, q8, #7
   5633c:	ee33 1b90 	vmov.32	r1, d19[1]
   56340:	ee32 4b90 	vmov.32	r4, d18[1]
   56344:	ee13 5b90 	vmov.32	r5, d19[0]
   56348:	ee12 6b90 	vmov.32	r6, d18[0]
   5634c:	4321      	orrs	r1, r4
   5634e:	ea46 0405 	orr.w	r4, r6, r5
   56352:	4321      	orrs	r1, r4
```

**Comment by hsivonen** [comment] 2019-02-05 11:19
Filed as a [`packed_simd` issue](https://github.com/rust-lang-nursery/packed_simd/issues/215).

**Comment by hsivonen** [comment] 2019-02-07 19:30
This is now fixed. Thank you for your help and patience.

**Closed** 2019-02-07 19:29 UTC
